name: 🐛 Bug report
description: Create a report to help us improve the library
labels: "type: bug"
assignees: frgfm

body:
  - type: markdown
    attributes:
      value: >
        #### Before reporting a bug, please check that the issue hasn't already been addressed in [the existing and past issues](https://github.com/quack-ai/companion/issues?q=is%3Aissue).
  - type: textarea
    attributes:
      label: Bug description
      description: |
        A clear and concise description of what the bug is.

        Please explain the result you observed and the behavior you were expecting.
      placeholder: |
        A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Minimal steps to reproduce the bug
      description: |
        Sample steps to reproduce the problem.

        Please specify what we need to do to reproduce the behaviour.
      placeholder: |
        Sample step to reproduce the problem
    validations:
      required: true
  - type: textarea
    attributes:
      label: Error traceback
      description: |
        The error message you received running the code snippet, with the full traceback.

        Please wrap your error message with ```` ```triple quotes blocks``` ```` for readability.
      placeholder: |
        ```
        The error message you got, with the full traceback.
        ```
    validations:
      required: true
  - type: textarea
    attributes:
      label: Environment
      description: |
        Please press Ctrl/Cmd+Shift+G, then paste the content of your clipboard below.
    validations:
      required: true
  - type: markdown
    attributes:
      value: >
        Thanks for helping us improve the library!
